activity:
  max_session: 1200
  min_break: 5
  max_blink_interval: 10
  ai_confidence_threshold: 0.9
  eye_crop_height: 35
  blink_reminder_type: NONE
  break_reminder_type: NONE
video:
  camera_index: 0
  show_camera: false
  debug_mode: false
