---
activity:
  max_session: 1200
  min_break: 20
  max_blink_interval: 10
  ai_confidence_threshold: 0.9
  eye_crop_height: 30
  reminder_type_values:
    - VISUAL
    - VOICE
    - VOICE_LONG
  reminder_type: VISUAL
video:
  camera_index: 1
  show_camera: true
  debug_mode: true
