activity:
  max_session: 1200
  min_break: 10
  max_blink_interval: 10
  ai_confidence_threshold: 0.9
  eye_crop_height: 30
  # reminder_type_values:
  #   - NONE
  #   - VISUAL
  #   - VOICE
  #   - VOICE_LONG
  reminder_type: VOICE_LONG
video:
  camera_index: 2
  show_camera: false
  debug_mode: true
